apiVersion: v1
kind: Service
metadata:
  name: storefront-graphql-api
  labels:
    app: storefront-graphql-api
spec:
  selector:
    app: storefront-graphql-api
  ports:
  - port: 8080
    targetPort: 8080
